replicaCount: 3
image:
  name: hyperledger/besu:25.8.0
  pullPolicy: IfNotPresent
service:
  name: besu
  headless: true
  ports:
    - name: ethapi
      port: 8545
      targetPort: 8545
    - name: engineapi
      port: 8550
      targetPort: 8550
    - name: p2p
      port: 30303
      targetPort: 30303
    - name: metrics
      port: 9545
      targetPort: 9545
persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: ""
configFiles:
  privateKey: |
    0xf3f61f30399831b8b6b00b67fd357faa3a641768846e6df25fd9990f151e3846
  configsToml: |
    data-path="/opt/besu/data"
    host-allowlist=["*"]
    sync-mode="FULL"
    p2p-port=30303

    min-gas-price=0

    # engine
    engine-host-allowlist=["*"]
    engine-rpc-port=8550
    engine-jwt-disabled=true

    # rpc
    rpc-http-enabled=true
    rpc-http-host="0.0.0.0"
    rpc-http-port=8545
    rpc-http-cors-origins=["*"]
    rpc-http-api=["ADMIN","ENGINE","DEBUG","NET","ETH","WEB3","PLUGINS"]
    rpc-http-max-active-connections=200

    # ws
    rpc-ws-enabled=true
    rpc-ws-host="0.0.0.0"
    rpc-ws-port=8546
    rpc-ws-api=["ADMIN","TXPOOL","WEB3","ETH","NET","PERM"]
    rpc-ws-max-active-connections=200

    # graphql
    graphql-http-enabled=false

    # metrics
    metrics-enabled=true
    metrics-host="0.0.0.0"
    metrics-port=9545

    # database
    data-storage-format="BONSAI"
    bonsai-limit-trie-logs-enabled=false
    bonsai-historical-block-limit=1024
    Xsnapsync-server-enabled=true

    # mining
    Xpos-block-creation-repetition-min-duration=100
  genesisJson: |
    {
      "@_WARNING": "THIS FILE IS FOR LOCAL DEVELOPMENT ONLY! DO NOT REUSE ELSEWHERE",
      "config": {
        "chainId": 1337,
        "homesteadBlock": 0,
        "eip150Block": 0,
        "eip155Block": 0,
        "eip158Block": 0,
        "byzantiumBlock": 0,
        "constantinopleBlock": 0,
        "petersburgBlock": 0,
        "istanbulBlock": 0,
        "berlinBlock": 0,
        "londonBlock": 0,
        "terminalTotalDifficulty": 0,
        "shanghaiTime": 0,
        "cancunTime": 0,
        "pragueTime": 0,
        "depositContractAddress": "0x4242424242424242424242424242424242424242",
        "withdrawalRequestContractAddress": "0x00000961ef480eb55e80d19ad83579a64c007002",
        "consolidationRequestContractAddress": "0x0000bbddc7ce488642fb579f8b00f3a590007251",
        "clique": {
          "createemptyblocks": false,
          "blockperiodseconds": 1,
          "epochlength": 1
        }
      },
      "coinbase": "0x0000000000000000000000000000000000000000",
      "difficulty": "0x1",
      "extraData": "0x00000000000000000000000000000000000000000000000000000000000000006d976c9b8ceee705d4fe8699b44e5eb58242f4840000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      "gasLimit": "0x1C9C380",
      "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
      "nonce": "0x0",
      "timestamp": "0x645580D1",
      "baseFeePerGas": "0x7",
      "@_WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
      "alloc": {
        "0x0000F90827F1C53a10cb7A02335B175320002935": {
          "balance": "0",
          "nonce": "1",
          "code": "0x3373fffffffffffffffffffffffffffffffffffffffe14604657602036036042575f35600143038111604257611fff81430311604257611fff9006545f5260205ff35b5f5ffd5b5f35611fff60014303065500"
        },
        "0x00000961Ef480Eb55e80D19ad83579A64c007002": {
          "balance": "0",
          "nonce": "1",
          "code": "0x3373fffffffffffffffffffffffffffffffffffffffe1460cb5760115f54807fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff146101f457600182026001905f5b5f82111560685781019083028483029004916001019190604d565b909390049250505036603814608857366101f457346101f4575f5260205ff35b34106101f457600154600101600155600354806003026004013381556001015f35815560010160203590553360601b5f5260385f601437604c5fa0600101600355005b6003546002548082038060101160df575060105b5f5b8181146101835782810160030260040181604c02815460601b8152601401816001015481526020019060020154807fffffffffffffffffffffffffffffffff00000000000000000000000000000000168252906010019060401c908160381c81600701538160301c81600601538160281c81600501538160201c81600401538160181c81600301538160101c81600201538160081c81600101535360010160e1565b910180921461019557906002556101a0565b90505f6002555f6003555b5f54807fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff14156101cd57505f5b6001546002828201116101e25750505f6101e8565b01600290035b5f555f600155604c025ff35b5f5ffd",
          "storage": {
            "0x0000000000000000000000000000000000000000000000000000000000000000": "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"
          }
        },
        "0x0000BBdDc7CE488642fb579F8B00f3a590007251": {
          "balance": "0",
          "nonce": "1",
          "code": "0x3373fffffffffffffffffffffffffffffffffffffffe1460d35760115f54807fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1461019a57600182026001905f5b5f82111560685781019083028483029004916001019190604d565b9093900492505050366060146088573661019a573461019a575f5260205ff35b341061019a57600154600101600155600354806004026004013381556001015f358155600101602035815560010160403590553360601b5f5260605f60143760745fa0600101600355005b6003546002548082038060021160e7575060025b5f5b8181146101295782810160040260040181607402815460601b815260140181600101548152602001816002015481526020019060030154905260010160e9565b910180921461013b5790600255610146565b90505f6002555f6003555b5f54807fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff141561017357505f5b6001546001828201116101885750505f61018e565b01600190035b5f555f6001556074025ff35b5f5ffd",
          "storage": {
            "0x0000000000000000000000000000000000000000000000000000000000000000": "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"
          }
        },
        "1b9abeec3215d8ade8a33607f2cf0f4f60e5f0d0": {
          "balance": "90000000000000000000000",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "@privateKey": "0x1dd171cec7e2995408b5513004e8207fe88d6820aeff0d82463b3e41df251aae",
          "@comment": "Contract deployer account"
        },
        "fe3b557e8fb62b89f4916b721be55ceb828dbd73": {
          "balance": "90000000000000000000001",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "@privateKey": "8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63",
          "@comment": "account 1, can be used as end user"
        },
        "627306090abaB3A6e1400e9345bC60c78a8BEf57": {
          "balance": "90000000000000000000002",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "@privateKey": "c87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3",
          "@comment": "account 2, can be used as end user"
        },
        "f17f52151EbEF6C7334FAD080c5704D77216b732": {
          "balance": "90000000000000000000003",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "@privateKey": "ae6ae8e5ccbfb04590405997ee2d52d2b330726137b875053c36d94e974d162f",
          "@comment": "account 3, can be used as end user"
        },
        "6d26dcc30a1693043aefa35ed9171c16da53f275": {
          "balance": "90000000000000000000004",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "@privateKey": "0x47629fbb4a7ad7772b4d1cc92f26b325577b70f1ed5940e1859b92d690f8a2bf",
          "@comment": "account 4, can be used as end user"
        },
        "e00cad48944330a60bbaedfbf2e0ac97e9762a1e": {
          "balance": "90000000000000000000005",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "@privateKey": "0x4f78823f38639b9ef15392eb8024ace1d7b991ea820b0dd36a15d14d1a6785",
          "@comment": "account 5, can be used as end user"
        },
        "2257ae433e214df824eb2ade79d2b305ca61a4f4": {
          "balance": "90000000000000000000006",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "@privateKey": "0x327456c797d6300e11051c0c19b9dbe480fe57cdfcb8033d313e80c7c2e10369",
          "@comment": "account 6, can be used as end user"
        },
        "0d4278da2f55cf21a014b7fee0a2cb799ce17ede": {
          "balance": "90000000000000000000007",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "@privateKey": "0x9ffda2814ee771e0af8018aeea65f9eabd47ea9f2a5b628a4571adeafea692d1",
          "@comment": "account 7, can be used as end user"
        },
        "994f4c82683f666d13d03a131078f1b94777790c": {
          "balance": "90000000000000000000008",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "@privateKey": "0xcd3a170ec22b2f3e4aee76356df0c34712db8c24f8d836bce1e4a79299c87053",
          "@comment": "account 8, can be used as end user"
        },
        "9d14ef14d4c90436a062efd7dc8354a7ded9712e": {
          "balance": "90000000000000000000009",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "@privateKey": "0x4a954bb197f7a27a5427f29180fbfd0b32ee0344b4f85c8184ca593cf152866a",
          "@comment": "account 9, can be used as end user"
        },
        "29a6b94168f04956c6fd1a2c3fdd1f6f7c468148": {
          "balance": "900000000000000000000010",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "@privateKey": "0x745dda33b5d813bda7f52d646a56498c1539290f59d064b13161f84a1f0a7b4b",
          "@comment": "account 10, can be used as end user"
        },
        "dca74800d7ce103a5e6a3f6028ab0963c46e7422": {
          "balance": "900000000000000000000011",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "@privateKey": "0x75b9700016469b0d7f12c0d6a0225cd9a59818a4bd1437cf9583ca0ffa1d111a",
          "@comment": "account 11, can be used as end user"
        },
        "9ad149426800dc9e65754a5ceab6bc1f41cc92a7": {
          "balance": "900000000000000000000012",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "@privateKey": "0xe08f03f96ff2f4e107a50da222e281db39cd528c8c35e25a17f0a71a4d279da5",
          "@comment": "account 12, can be used as end user"
        },
        "b3c150df38e91149e260c3233f3121810d4d2976": {
          "balance": "900000000000000000000013",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "@privateKey": "0x7303d2fadd895018075cbe76d8a700bc65b4a1b8641b97d660533f0e029e3954",
          "@comment": "account 13, can be used as end user"
        },
        "42232eab8cfd6b489efe79d3bdcc12f07a9fbac6": {
          "balance": "900000000000000000000014",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "@privateKey": "0xc5453712de35e7dc2c599b5f86df5d4f0de442d86a2865cfe557acd6d131aa6f",
          "@comment": "account 14, can be used as end user"
        },
        "30b080749e44112c3e679c5e4117dd2d884ec7da": {
          "balance": "900000000000000000000015",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "@privateKey": "0xa8cc1b4bf5cd228cfe63c1b73a5515721e72b487cf8b82a285023aa0ed1ef839",
          "@comment": "account 15, can be used as end user"
        },
        "82f93ea98b24441dc3e0b2413cc1cbb02f33d7e5": {
          "balance": "900000000000000000000016",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "@privateKey": "0x8c1c8a65947b79ef919261364e9044d89ffe26fb764d8cd72db0446d6cf56664",
          "@comment": "account 16, can be used as end user"
        },
        "bae3c3fcd73ccf7755ec8a10664f218ad6bbc775": {
          "balance": "900000000000000000000017",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "@privateKey": "0xb35972d9380d1be620a2c61da77f68f127ef248ec55e1bc6033d20a7e13ef3fa",
          "@comment": "account 17, can be used as end user"
        },
        "54d450f4d728da50f1271a1700b42657940324aa": {
          "balance": "900000000000000000000018",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "@privateKey": "0x234d87442cf7d43841fbe280febcdfabfb646added67bc19f7e42a5483f614c4",
          "@comment": "account 18, can be used as end user"
        },
        "d42e308fc964b71e18126df469c21b0d7bcb86cc": {
          "balance": "900000000000000000000019",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "@privateKey": "0x4d01ae6487860981699236a58b68f807ee5f17b12df5740b85cf4c4653be0f55",
          "@comment": "Message anchorer account"
        },
        "c8c92fe825d8930b9357c006e0af160dfa727a62": {
          "balance": "900000000000000000000020",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "@privateKey": "0xfcf854e0a0bc6fd7e97d7050e61a362c915cecd6767a32267b22e8b7af572e58",
          "@comment": "account 20, can be used as end user"
        },
        "e537D669CA013d86EBeF1D64e40fC74CADC91987": {
          "balance": "900000000000000000000021",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "comment": "account 21, can be used as end user"
        },
        "8cdcc370846c9f669489227465f80e6cc4ecd050": {
          "balance": "90000000000000000000000",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "@privateKey": "0xb17202c37cce9498e6f7dcdc1abd207802d09b5eee96677ea219ac867a198b91",
          "@comment": "Account used for smart contract deployment on L1 and L2"
        },
        "d0584d4d37157f7105a4b41ed8ecbdfafdb2547f": {
          "balance": "90000000000000000000000",
          "@WARNING": "FOR LOCAL DEV ONLY - DO NOT REUSE THESE KEYS ELSEWHERE",
          "@privateKey": "0x202454d1b4e72c41ebf58150030f649648d3cf5590297fb6718e27039ed9c86d",
          "@comment": "Operator account"
        },
        "0x000F3df6D732807Ef1319fB7B8bB8522d0Beac02": {
          "balance": "0",
          "nonce": "1",
          "code": "0x3373fffffffffffffffffffffffffffffffffffffffe14604d57602036146024575f5ffd5b5f35801560495762001fff810690815414603c575f5ffd5b62001fff01545f5260205ff35b5f5ffd5b62001fff42064281555f359062001fff015500"
        }
      }
    }
  log4j: |
    <?xml version="1.0" encoding="UTF-8"?>
    <Configuration status="INFO" monitorInterval="2">
    <Appenders>
      <Console name="Console" target="SYSTEM_OUT">
        <PatternLayout pattern="%d{yyyy-MM-dd HH:mm:ss.SSSZZZ} | %t | %-5level | %c{1} | %msg %throwable%n" />
      </Console>
    </Appenders>
    <Loggers>
      <Logger name="org.hyperledger.besu" level="WARN" additivity="false"/>
      <!-- to avoid annoying message "INFO ... No sync target, waiting for peers. Current peers: 0" change to WARN-->
      <Logger name="org.hyperledger.besu.ethereum.eth.sync.fullsync.FullSyncTargetManager" level="WARN" additivity="false" />
      <Logger name="org.hyperledger.besu.ethereum.mainnet.BlockHeaderValidator" level="DEBUG" additivity="false" />
      <Logger name="org.hyperledger.besu.ethereum.mainnet.BlockBodyValidator" level="DEBUG" additivity="false" />
      <Logger name="org.hyperledger.besu.consensus.clique.headervalidationrules" level="DEBUG" additivity="false" />
      <Logger name="org.hyperledger.besu.ethereum.blockcreation" level="INFO" additivity="false" />
      <Logger name="org.hyperledger.besu.consensus.merge.blockcreation" level="INFO" additivity="false" />
      <Logger name="org.hyperledger.besu.ethereum.api.jsonrpc" level="TRACE" additivity="false" />
      <Logger name="org.hyperledger.besu.ethereum.eth.transactions.TransactionPool" level="TRACE" additivity="false" />
      <Logger name="org.hyperledger.besu.ethereum.api.jsonrpc.internal" level="DEBUG" additivity="false" />
      <Logger name="org.hyperledger.besu.ethereum.eth.manager.snap" level="DEBUG" additivity="false /"
      <Logger name="net.consensys.linea.sequencer.txselection.selectors" level="DEBUG" />
      <Logger name="org.hyperledger.besu.ethereum.blockcreation.txselection.BlockTransactionSelector" level="INFO" />
      <Logger name="io.opentelemetry" level="WARN" additivity="false" />
    </Loggers>
    <Filters>
      <LevelRangeFilter maxLevel="DEBUG" onMatch="ACCEPT" onMismatch="NEUTRAL" />
      <RegexFilter regex="Transaction selection result .*" useRawMsg="true" onMatch="ACCEPT" onMismatch="DENY" />
    </Filters>
    </Logger>
    <Root level="INFO">
      <AppenderRef ref="Console"/>
    </Root>
    </Loggers>
    </Configuration>

